-- =====================================================
-- ORACLE SCHEMAS FOR MICROSERVICE SYSTEM
-- =====================================================

-- ORDERS SERVICE USER
CREATE USER ORDERS_USER IDENTIFIED BY orders123;
GRANT CONNECT, RESOURCE TO ORDERS_USER;
ALTER USER ORDERS_USER QUOTA UNLIMITED ON USERS;

-- INVENTORY SERVICE USER
CREATE USER INVENTORY_USER IDENTIFIED BY inv123;
GRANT CONNECT, RESOURCE TO INVENTORY_USER;
ALTER USER INVENTORY_USER QUOTA UNLIMITED ON USERS;

-- CUSTOMERS SERVICE USER
CREATE USER CUSTOMERS_USER IDENTIFIED BY cust123;
GRANT CONNECT, RESOURCE TO CUSTOMERS_USER;
ALTER USER CUSTOMERS_USER QUOTA UNLIMITED ON USERS;

-- OPTIONAL: Verify users
SELECT username FROM dba_users WHERE username IN ('ORDERS_USER', 'INVENTORY_USER', 'CUSTOMERS_USER');

CREATE TABLE INVENTORY_USER.INVENTORY_STOCK 
(
  ID NUMBER NOT NULL 
, SKU_CODE VARCHAR2(100) NOT NULL 
, QUANTITY NUMBER 
, INVENTORY_ITEM_ID NUMBER NOT NULL 
, CONSTRAINT INVENTORY_STOCK_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

alter table "INVENTORY_USER"."INVENTORY_STOCK" add constraint INVENTORY_ITEM_ID_FK foreign key("INVENTORY_ITEM_ID") references "INVENTORY_USER"."INVENTORY_ITEM"("ID");


