FROM jenkins/jenkins:lts-jdk21

USER root

# Install Docker CLI (client only)
RUN apt-get update && \
    apt-get install -y ca-certificates curl && \
    curl -fsSL https://get.docker.com | sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
