FROM jenkins/jenkins:lts-jdk17

USER root

# Install required native libraries for NodeJS
RUN apt-get update && \
    apt-get install -y libatomic1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
